// Generated by rstantools.  Do not edit by hand.

/*
    stackr is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    stackr is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with stackr.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.19.1
#include <stan/model/model_header.hpp>
namespace model_stacking_weights_crps_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_stacking_weights_crps");
    reader.add_event(78, 76, "end", "model_stacking_weights_crps");
    return reader;
}
template <typename T1__, typename T2__, typename T3__>
typename boost::math::tools::promote_args<T1__, T2__, T3__>::type
CRPS_pointwise(const int& K,
                   const Eigen::Matrix<T1__, Eigen::Dynamic, 1>& mean_bias,
                   const Eigen::Matrix<T2__, Eigen::Dynamic, Eigen::Dynamic>& entropy,
                   const Eigen::Matrix<T3__, Eigen::Dynamic, 1>& w, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T1__, T2__, T3__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 4;
        local_scalar_t__ entropy_aggregate(DUMMY_VAR__);
        (void) entropy_aggregate;  // dummy to suppress unused var warning
        stan::math::initialize(entropy_aggregate, DUMMY_VAR__);
        stan::math::fill(entropy_aggregate, DUMMY_VAR__);
        stan::math::assign(entropy_aggregate,quad_form(entropy, w));
        current_statement_begin__ = 5;
        return stan::math::promote_scalar<fun_return_scalar_t__>((dot_product(mean_bias, w) - (0.5 * entropy_aggregate)));
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct CRPS_pointwise_functor__ {
    template <typename T1__, typename T2__, typename T3__>
        typename boost::math::tools::promote_args<T1__, T2__, T3__>::type
    operator()(const int& K,
                   const Eigen::Matrix<T1__, Eigen::Dynamic, 1>& mean_bias,
                   const Eigen::Matrix<T2__, Eigen::Dynamic, Eigen::Dynamic>& entropy,
                   const Eigen::Matrix<T3__, Eigen::Dynamic, 1>& w, std::ostream* pstream__) const {
        return CRPS_pointwise(K, mean_bias, entropy, w, pstream__);
    }
};
#include <stan_meta_header.hpp>
class model_stacking_weights_crps : public prob_grad {
private:
        int K;
        int T;
        int S;
        int R;
        std::vector<std::vector<matrix_d> > predict_sample_mat;
        std::vector<vector_d> y;
        vector_d lambda;
        vector_d gamma;
        double dirichlet_alpha;
        std::vector<std::vector<vector_d> > mean_bias;
        std::vector<std::vector<matrix_d> > entropy;
public:
    model_stacking_weights_crps(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_stacking_weights_crps(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_stacking_weights_crps_namespace::model_stacking_weights_crps";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 11;
            context__.validate_dims("data initialization", "K", "int", context__.to_vec());
            K = int(0);
            vals_i__ = context__.vals_i("K");
            pos__ = 0;
            K = vals_i__[pos__++];
            check_greater_or_equal(function__, "K", K, 2);
            current_statement_begin__ = 12;
            context__.validate_dims("data initialization", "T", "int", context__.to_vec());
            T = int(0);
            vals_i__ = context__.vals_i("T");
            pos__ = 0;
            T = vals_i__[pos__++];
            check_greater_or_equal(function__, "T", T, 1);
            current_statement_begin__ = 13;
            context__.validate_dims("data initialization", "S", "int", context__.to_vec());
            S = int(0);
            vals_i__ = context__.vals_i("S");
            pos__ = 0;
            S = vals_i__[pos__++];
            check_greater_or_equal(function__, "S", S, 1);
            current_statement_begin__ = 14;
            context__.validate_dims("data initialization", "R", "int", context__.to_vec());
            R = int(0);
            vals_i__ = context__.vals_i("R");
            pos__ = 0;
            R = vals_i__[pos__++];
            check_greater_or_equal(function__, "R", R, 1);
            current_statement_begin__ = 16;
            validate_non_negative_index("predict_sample_mat", "S", S);
            validate_non_negative_index("predict_sample_mat", "K", K);
            validate_non_negative_index("predict_sample_mat", "T", T);
            validate_non_negative_index("predict_sample_mat", "R", R);
            context__.validate_dims("data initialization", "predict_sample_mat", "matrix_d", context__.to_vec(T,R,S,K));
            predict_sample_mat = std::vector<std::vector<Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> > >(T, std::vector<Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> >(R, Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(S, K)));
            vals_r__ = context__.vals_r("predict_sample_mat");
            pos__ = 0;
            size_t predict_sample_mat_j_2_max__ = K;
            size_t predict_sample_mat_j_1_max__ = S;
            size_t predict_sample_mat_k_0_max__ = T;
            size_t predict_sample_mat_k_1_max__ = R;
            for (size_t j_2__ = 0; j_2__ < predict_sample_mat_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < predict_sample_mat_j_1_max__; ++j_1__) {
                    for (size_t k_1__ = 0; k_1__ < predict_sample_mat_k_1_max__; ++k_1__) {
                        for (size_t k_0__ = 0; k_0__ < predict_sample_mat_k_0_max__; ++k_0__) {
                            predict_sample_mat[k_0__][k_1__](j_1__, j_2__) = vals_r__[pos__++];
                        }
                    }
                }
            }
            current_statement_begin__ = 17;
            validate_non_negative_index("y", "T", T);
            validate_non_negative_index("y", "R", R);
            context__.validate_dims("data initialization", "y", "vector_d", context__.to_vec(R,T));
            y = std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> >(R, Eigen::Matrix<double, Eigen::Dynamic, 1>(T));
            vals_r__ = context__.vals_r("y");
            pos__ = 0;
            size_t y_j_1_max__ = T;
            size_t y_k_0_max__ = R;
            for (size_t j_1__ = 0; j_1__ < y_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < y_k_0_max__; ++k_0__) {
                    y[k_0__](j_1__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 19;
            validate_non_negative_index("lambda", "T", T);
            context__.validate_dims("data initialization", "lambda", "vector_d", context__.to_vec(T));
            lambda = Eigen::Matrix<double, Eigen::Dynamic, 1>(T);
            vals_r__ = context__.vals_r("lambda");
            pos__ = 0;
            size_t lambda_j_1_max__ = T;
            for (size_t j_1__ = 0; j_1__ < lambda_j_1_max__; ++j_1__) {
                lambda(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 20;
            validate_non_negative_index("gamma", "R", R);
            context__.validate_dims("data initialization", "gamma", "vector_d", context__.to_vec(R));
            gamma = Eigen::Matrix<double, Eigen::Dynamic, 1>(R);
            vals_r__ = context__.vals_r("gamma");
            pos__ = 0;
            size_t gamma_j_1_max__ = R;
            for (size_t j_1__ = 0; j_1__ < gamma_j_1_max__; ++j_1__) {
                gamma(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 21;
            context__.validate_dims("data initialization", "dirichlet_alpha", "double", context__.to_vec());
            dirichlet_alpha = double(0);
            vals_r__ = context__.vals_r("dirichlet_alpha");
            pos__ = 0;
            dirichlet_alpha = vals_r__[pos__++];
            // initialize transformed data variables
            current_statement_begin__ = 26;
            validate_non_negative_index("mean_bias", "K", K);
            validate_non_negative_index("mean_bias", "T", T);
            validate_non_negative_index("mean_bias", "R", R);
            mean_bias = std::vector<std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > >(T, std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> >(R, Eigen::Matrix<double, Eigen::Dynamic, 1>(K)));
            stan::math::fill(mean_bias, DUMMY_VAR__);
            current_statement_begin__ = 27;
            validate_non_negative_index("entropy", "K", K);
            validate_non_negative_index("entropy", "K", K);
            validate_non_negative_index("entropy", "T", T);
            validate_non_negative_index("entropy", "R", R);
            entropy = std::vector<std::vector<Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> > >(T, std::vector<Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> >(R, Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(K, K)));
            stan::math::fill(entropy, DUMMY_VAR__);
            // execute transformed data statements
            current_statement_begin__ = 30;
            for (int r = 1; r <= R; ++r) {
                current_statement_begin__ = 31;
                for (int t = 1; t <= T; ++t) {
                    current_statement_begin__ = 32;
                    for (int k = 1; k <= K; ++k) {
                        current_statement_begin__ = 36;
                        stan::model::assign(mean_bias, 
                                    stan::model::cons_list(stan::model::index_uni(t), stan::model::cons_list(stan::model::index_uni(r), stan::model::cons_list(stan::model::index_uni(k), stan::model::nil_index_list()))), 
                                    0, 
                                    "assigning variable mean_bias");
                        current_statement_begin__ = 37;
                        for (int s = 1; s <= S; ++s) {
                            current_statement_begin__ = 38;
                            stan::model::assign(mean_bias, 
                                        stan::model::cons_list(stan::model::index_uni(t), stan::model::cons_list(stan::model::index_uni(r), stan::model::cons_list(stan::model::index_uni(k), stan::model::nil_index_list()))), 
                                        (stan::model::rvalue(mean_bias, stan::model::cons_list(stan::model::index_uni(t), stan::model::cons_list(stan::model::index_uni(r), stan::model::cons_list(stan::model::index_uni(k), stan::model::nil_index_list()))), "mean_bias") + (stan::math::fabs((get_base1(get_base1(get_base1(predict_sample_mat, t, "predict_sample_mat", 1), r, "predict_sample_mat", 2), s, k, "predict_sample_mat", 3) - get_base1(get_base1(y, r, "y", 1), t, "y", 2))) / S)), 
                                        "assigning variable mean_bias");
                        }
                    }
                }
            }
            current_statement_begin__ = 45;
            for (int r = 1; r <= R; ++r) {
                current_statement_begin__ = 46;
                for (int t = 1; t <= T; ++t) {
                    current_statement_begin__ = 49;
                    stan::model::assign(entropy, 
                                stan::model::cons_list(stan::model::index_uni(t), stan::model::cons_list(stan::model::index_uni(r), stan::model::nil_index_list())), 
                                rep_matrix(0, K, K), 
                                "assigning variable entropy");
                    current_statement_begin__ = 50;
                    for (int k1 = 1; k1 <= K; ++k1) {
                        current_statement_begin__ = 51;
                        for (int k2 = 1; k2 <= k1; ++k2) {
                            current_statement_begin__ = 52;
                            for (int s1 = 1; s1 <= S; ++s1) {
                                current_statement_begin__ = 53;
                                stan::model::assign(entropy, 
                                            stan::model::cons_list(stan::model::index_uni(t), stan::model::cons_list(stan::model::index_uni(r), stan::model::cons_list(stan::model::index_uni(k1), stan::model::cons_list(stan::model::index_uni(k2), stan::model::nil_index_list())))), 
                                            (stan::model::rvalue(entropy, stan::model::cons_list(stan::model::index_uni(t), stan::model::cons_list(stan::model::index_uni(r), stan::model::cons_list(stan::model::index_uni(k1), stan::model::cons_list(stan::model::index_uni(k2), stan::model::nil_index_list())))), "entropy") + ((1.0 / pow(S, 2)) * sum(stan::math::fabs(subtract(get_base1(get_base1(get_base1(predict_sample_mat, t, "predict_sample_mat", 1), r, "predict_sample_mat", 2), s1, k1, "predict_sample_mat", 3), stan::model::rvalue(predict_sample_mat, stan::model::cons_list(stan::model::index_uni(t), stan::model::cons_list(stan::model::index_uni(r), stan::model::cons_list(stan::model::index_min_max(1, S), stan::model::cons_list(stan::model::index_uni(k2), stan::model::nil_index_list())))), "predict_sample_mat")))))), 
                                            "assigning variable entropy");
                            }
                        }
                    }
                    current_statement_begin__ = 56;
                    for (int k1 = 1; k1 <= (K - 1); ++k1) {
                        current_statement_begin__ = 57;
                        for (int k2 = (k1 + 1); k2 <= K; ++k2) {
                            current_statement_begin__ = 58;
                            stan::model::assign(entropy, 
                                        stan::model::cons_list(stan::model::index_uni(t), stan::model::cons_list(stan::model::index_uni(r), stan::model::cons_list(stan::model::index_uni(k1), stan::model::cons_list(stan::model::index_uni(k2), stan::model::nil_index_list())))), 
                                        get_base1(get_base1(get_base1(entropy, t, "entropy", 1), r, "entropy", 2), k2, k1, "entropy", 3), 
                                        "assigning variable entropy");
                        }
                    }
                }
            }
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 64;
            validate_non_negative_index("weights", "K", K);
            num_params_r__ += (K - 1);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_stacking_weights_crps() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 64;
        if (!(context__.contains_r("weights")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable weights missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("weights");
        pos__ = 0U;
        validate_non_negative_index("weights", "K", K);
        context__.validate_dims("parameter initialization", "weights", "vector_d", context__.to_vec(K));
        Eigen::Matrix<double, Eigen::Dynamic, 1> weights(K);
        size_t weights_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < weights_j_1_max__; ++j_1__) {
            weights(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.simplex_unconstrain(weights);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable weights: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 64;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> weights;
            (void) weights;  // dummy to suppress unused var warning
            if (jacobian__)
                weights = in__.simplex_constrain(K, lp__);
            else
                weights = in__.simplex_constrain(K);
            // model body
            current_statement_begin__ = 70;
            for (int t = 1; t <= T; ++t) {
                current_statement_begin__ = 71;
                for (int r = 1; r <= R; ++r) {
                    current_statement_begin__ = 72;
                    lp_accum__.add(((-(get_base1(lambda, t, "lambda", 1)) * get_base1(gamma, r, "gamma", 1)) * CRPS_pointwise(K, get_base1(get_base1(mean_bias, t, "mean_bias", 1), r, "mean_bias", 2), get_base1(get_base1(entropy, t, "entropy", 1), r, "entropy", 2), weights, pstream__)));
                }
            }
            current_statement_begin__ = 74;
            lp_accum__.add(dirichlet_log<propto__>(weights, rep_vector(dirichlet_alpha, K)));
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("weights");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back(K);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_stacking_weights_crps_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        Eigen::Matrix<double, Eigen::Dynamic, 1> weights = in__.simplex_constrain(K);
        size_t weights_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < weights_j_1_max__; ++j_1__) {
            vars__.push_back(weights(j_1__));
        }
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            if (!include_gqs__ && !include_tparams__) return;
            if (!include_gqs__) return;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    static std::string model_name() {
        return "model_stacking_weights_crps";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t weights_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < weights_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "weights" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
        }
        if (!include_gqs__) return;
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t weights_j_1_max__ = (K - 1);
        for (size_t j_1__ = 0; j_1__ < weights_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "weights" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
        }
        if (!include_gqs__) return;
    }
}; // model
}  // namespace
typedef model_stacking_weights_crps_namespace::model_stacking_weights_crps stan_model;
#endif
